### ISSUE TITLE
error while compiling cudpp 

### ISSUE THREAD

**Issue by egodfred** [NVlabs/cub#118]
[ 25%] Building NVCC (Device) object src/cudpp/CMakeFiles/cudpp.dir/app/cudpp_generated_multisplit_app.cu.o
[...]/cudpp/src/cudpp/app/multisplit_app.cu(1919): error: namespace "cub" has no member "CachingDeviceAllocator"

1 error detected in the compilation of "/tmp/tmpxft_00003ceb_00000000-7_multisplit_app.cpp1.ii".
CMake Error at cudpp_generated_multisplit_app.cu.o.cmake:266 (message):
  Error generating file
  [...]/cudpp_build/src/cudpp/CMakeFiles/cudpp.dir/app/./cudpp_generated_multisplit_app.cu.o

**Comment by dumerrill** [comment]
This is a CUDPP issue.  Maybe they are not including the proper header (https://github.com/NVlabs/cub/blob/1.7.4/cub/util_allocator.cuh)?

**Comment by nodnerb93** [comment]
I was able to fix this problem by adding 
#include "util_allocator.cuh" to my cub.cuh file.

**Comment by makeclean** [comment]
+1

**Comment by jmshi321** [comment]
+1
