### ISSUE TITLE
Possible bug in cub::DeviceRadixSort::SortPairs() when begin/end bit parameters are set

### ISSUE THREAD

**Issue by sola-aina** [NVlabs/cub#119]
Please refer to the sample program at:
https://devtalk.nvidia.com/default/topic/1026095/cuda-programming-and-performance/setting-begin-end-bit-parameters-in-cub-deviceradixsort-sortpairs-/post/5219337/#5219337

The problem appears to be that when the begin/end bit parameters are specified the post-sort keys are no longer unique. This is not an issue when the parameters are not specified. 

I have tested on Ubuntu (CUDA 8 Fermi GPU) and Windows 7 (CUDA 9 Quadro K600 GPU).

**Comment by RaulPPelaez** [comment]
This one should be closed, it has been solved in the devtalk and it is not a bug in cub.

**Comment by sola-aina** [comment]
Agreed.
