### ISSUE TITLE
How to compile code with cmake

### ISSUE THREAD

**Issue by ztdepztdep** [NVlabs/cub#138]
Dear friends:
     I want to use CUB to conduct reduction in my cuda project. My project is compiled with kdevelop5.2 cmake. 
     Could you please give me some information about how to compile cub function with cmake.
  Regards

**Comment by rob3c** [comment]
This is what I do to wrap CUB for easy inclusion in subprojects

excerpts from a root `CMakeLists.txt`:
```cmake
# ...
set(CTX "root")
set(MY_PROJECT_VERSION 0.1.0)
message("[${CTX}] MY_PROJECT_VERSION ${MY_PROJECT_VERSION}")
# ...
set(CUB_LIBRARY_ROOT /path/to/local/cub/git/repo)
if (NOT EXISTS ${CUB_LIBRARY_ROOT})
  message(WARNING "[${CTX}] CANNOT FIND CUB LIBRARY - MAKE ENTRY IN ROOT CMakeLists.txt")
else()
  message("[${CTX}] CUB_LIBRARY_ROOT ${CUB_LIBRARY_ROOT}")
endif()
# make CLion happy - NOTE: must be before add_subdirectory calls!
include_directories(
  ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}
  ${CUB_LIBRARY_ROOT}
  # ...
)
# ...
add_library(cub INTERFACE IMPORTED)
target_include_directories(cub INTERFACE
  ${CUB_LIBRARY_ROOT}
  # ...
)
set_target_properties(cub PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${CUB_LIBRARY_ROOT}
  # ...
)
# ...
```

And then reference it in any subproject's `CMakeLists.txt`:
```cmake
# ...
project(my-subproject
  VERSION ${MY_PROJECT_VERSION}
  LANGUAGES CUDA CXX)
set(CTX ${PROJECT_NAME})
# ...
target_link_libraries(${PROJECT_NAME}
    PRIVATE
        cub
        # ...
)
# ...
```

**Comment by jipe4153** [comment]
There's no reason that CUB couldn't ship with an existing CMakeLists.txt file that could create a proper versioned package of this.

**Comment by jiapei100** [comment]
Same question here... How to compile, build and install CUB?

Cheers
Pei

**Comment by dumerrill** [comment]
CUB is simply a collection of header files to be incorporated by any CUDA application, and is agnostic of any particular OS platform, compiler chain, and build/make framework.  There are no shared objects or libraries to build/redistribute, so there's no need to for CUB to "lock into" any one specific build/make framework.

>  it seems we ONLY need to copy and paste the header files

Yes, basically.  To incorporate CUB into a project, you simply adjust your particular build framework's include-path (i.e., whatever is necessary to produce the `-I<cub-dir>` flag to `nvcc`) and `#include` the relevant CUB header files into application source.

**Comment by psteinb** [comment]
If technically possible, it maybe worth thinking about a single-header version of CUB. Tools like pcpp might be of help here: https://github.com/ned14/pcpp 
IIRC, catch and catch2 uses similar approaches. Just a thought.

**Comment by jipe4153** [comment]
> CUB is simply a collection of header files to be incorporated by any CUDA application, and is agnostic of any particular OS platform, compiler chain, and build/make framework. There are no shared objects or libraries to build/redistribute, so there's no need to for CUB to "lock into" any one specific build/make framework.
> 
> > it seems we ONLY need to copy and paste the header files
> 
> Yes, basically. To incorporate CUB into a project, you simply adjust your particular build framework's include-path (i.e., whatever is necessary to produce the `-I<cub-dir>` flag to `nvcc`) and `#include` the relevant CUB header files into application source.

Using CMAKE to package those headers will not lock you into any specific build system or OS.

Example use cases:

(1) A user clones CUB from github
(2) A user installs CUB to their system (windows/linux/whatever it's agnostic)
(3) The user can start using CUB in their modern build system:

`
# Locate installed CUB package on system
find_package(CUB 1.1.4 REQUIRED)
# Use CUB for my APP
target_link_libraries(myApp PRIVATE CUB)
`
Or the user may include CUB in their source tree (ex as a submodule):
`
# Locate CUB module in source
add_subdirectory(CUB)
# Use CUB for my APP
target_link_libraries(myApp PRIVATE CUB)
`
This is all completely independent of OS or underlying build system, it's a method of handling modular dependencies in source code.

In my fork of CUB I've added CMakeLists.txt with ~5 lines of code to achieve most of this behaviour. Plus some additional files to create install-able DEB/RPM/tar.gz/.. packages.

Modern CMAKE support is slowly becoming an expected standard in C++ projects, so much that the CMAKE architects encourage people to file a bug report if CMAKE support is missing :)

Highly recommed this:
https://www.slideshare.net/DanielPfeifer1/effective-cmake
