### ISSUE TITLE
DeviceSegmentedReduce out-of-memory error 

### ISSUE THREAD

**Issue by dorisnvidia** [NVlabs/cub#145]
Hi Duane, 

We encountered a memory error when using DeviceSegmentedReduce::Reduce, specifically, 	cudaErrorMemoryAllocation error in the reduce kernel DeviceSegmentedReduceKernel().  The error only occurs when we compile with -g -G debug flags, and when there are more than 4 floats in a struct. I think there is a bug somewhere in the cub, but I used gdb and it does not give me much info. 

Here is the step to reproduce the error:
1. compile the code with:
nvcc -g -G  -c -std=c++11 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70  -I/cm/extra/apps/CUDA.linux86-64/9.1.85_387.26/include -I/cm/extra/apps/cuDNN/9.1-v7.0.5/include -I/cm/extra/apps/CUDA.linux86-64/9.1.85_387.26/samples/common/inc -I/home/dorisp/TarBalls/cub-1.8.0 -I./ -o segmentedReduce.o segmentedReduce.cu
nvcc -g -G  -std=c++11 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70  -o segmentedReduce segmentedReduce.o -L/cm/extra/apps/CUDA.linux86-64/9.1.85_387.26/lib64

Then run:
./segmentedReduce
...
temp_storage_bytes = 1
CUDA error at segmentedReduce.cu:179 code=2(cudaErrorMemoryAllocation) "cub::DeviceSegmentedReduce::Reduce( d_temp_storage, temp_storage_bytes, d_in, d_out, num_segments, d_offsets, d_offsets + 1, reduceOp, initVal )"

2. compiler the code without -g -G, then it runs fine
nvcc  -c -std=c++11 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70  -I/cm/extra/apps/CUDA.linux86-64/9.1.85_387.26/include -I/cm/extra/apps/cuDNN/9.1-v7.0.5/include -I/cm/extra/apps/CUDA.linux86-64/9.1.85_387.26/samples/common/inc -I/home/dorisp/TarBalls/cub-1.8.0 -I./ -o segmentedReduce.o segmentedReduce.cu
nvcc  -std=c++11 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70  -o segmentedReduce segmentedReduce.o -L/cm/extra/apps/CUDA.linux86-64/9.1.85_387.26/lib64

./segmentedReduce 
...
Derive temp_storage_bytes...
no error
temp_storage_bytes = 1
no error
segmentedReduce output d_out is Correct!

3. Change Line 34, 
#def NUM 5 
from 5 to any number <=4. The code will run fine regardless compiling with or without -g -G. 

[segmentedReduce.cu.txt](https://github.com/NVlabs/cub/files/2368393/segmentedReduce.cu.txt)

**Comment by dorisnvidia** [comment]
Forgot to report the cuda version is 9.1.85_387.26, and cub 1.8.0.

**Comment by dumerrill** [comment]
Looking into it

**Comment by dumerrill** [comment]
Okay, the issue here is that compiling with -G (device debugging support) can require the runtime to allocate a lot of device storage behind the scenes when launching a kernel.  In this case, because you have already allocated so much memory (“workspace “ + “additional” allocations), you in fact are getting a legitimate out-of-memory exception when running the CUB kernel.  But it’s not CUB’s fault, nor is it a bug.  Your simplest remedies are either:
(a)	not compile with -G, or
(b)	use less memory

To illustrate, if you decrease the amount of extra memory (say to “free - 4011824128” bytes), everything runs fine.

So…. Not a bug.
