### ISSUE TITLE
CUDA error: invalid device function when DeviceRadixSort::SortKeys called from __host__ __device__ function

### ISSUE THREAD

**Issue by jaredhoberock** [NVlabs/cub#30]
The following program:

```
#if !defined(__CUDA_ARCH__) || (__CUDA_ARCH__>= 350 && defined(__CUDACC_RDC__))
#  define CUB_CDP 1
#endif

#include <thrust/device_vector.h>
#include <thrust/tabulate.h>
#include <thrust/functional.h>
#include <thrust/sort.h>
#include <thrust/copy.h>
#include <thrust/execution_policy.h>
#include <cub/device/device_radix_sort.cuh>
#include <cassert>

template<typename T>
__host__ __device__
cudaError_t cub_sort_n(T* first, size_t n)
{
  cudaError_t result = cudaSuccess;

#if !defined(__CUDA_ARCH__) || CUB_CDP
  // XXX the additional temporary storage bytes
  //     must be allocated on a 16b aligned address
  struct __align__(16) aligned_type {};

  if(n > 1)
  {
    cub::DoubleBuffer<T> double_buffer;

    // measure the number of additional temporary storage bytes required
    size_t num_additional_temp_storage_bytes = 0;

    cudaError_t error = cub::DeviceRadixSort::SortKeys(0, num_additional_temp_storage_bytes, double_buffer, static_cast<int>(n));
    if(error != cudaSuccess) return error;

    // allocate temporary storage for double buffer as well as additional bytes
    size_t num_double_buffer_bytes = n * sizeof(T);
    size_t num_aligned_double_buffer_bytes = thrust::detail::util::round_i(num_double_buffer_bytes, sizeof(aligned_type));
    size_t num_aligned_total_temporary_storage_bytes = num_aligned_double_buffer_bytes + num_additional_temp_storage_bytes;

    thrust::device_vector<char> temporary_storage(num_aligned_total_temporary_storage_bytes);

    void* additional_temp_storage_ptr = thrust::raw_pointer_cast(temporary_storage.data() + num_aligned_double_buffer_bytes);

    double_buffer.d_buffers[0] = thrust::raw_pointer_cast(&*first);
    double_buffer.d_buffers[1] = reinterpret_cast<T*>(thrust::raw_pointer_cast(temporary_storage.data()));

    result = cub::DeviceRadixSort::SortKeys(additional_temp_storage_ptr,
                                            num_additional_temp_storage_bytes,
                                            double_buffer,
                                            static_cast<int>(n));
    if(result != cudaSuccess) return result;

    if(double_buffer.Current() != 0)
    {
      T* temp_ptr = reinterpret_cast<T*>(double_buffer.d_buffers[1]);
      thrust::copy(thrust::device, temp_ptr, temp_ptr + n, first);
    }
  }
#else
  result = cudaErrorNotSupported;
#endif

  return result;
}


int main()
{
  size_t n = 2;

  thrust::host_vector<int> ref(n);

  // generate unsorted values
  thrust::tabulate(ref.begin(), ref.end(), thrust::placeholders::_1 % 1024);

  thrust::device_vector<int> data = ref;

  cudaError_t error = cub_sort_n(thrust::raw_pointer_cast(data.data()), data.size());
  if(error)
  {
    std::cerr << "CUDA error: " << cudaGetErrorString(error) << std::endl;
    std::exit(-1);
  }

  thrust::sort(ref.begin(), ref.end());

  assert(ref == data);

  assert(thrust::is_sorted(data.begin(), data.end()));

  return 0;
}
```

Yields the following output at runtime:

```
$ nvcc -I. repro.cu -run
CUDA error: invalid device function 
```

I believe the way that CUB uses the `CUB_CDP` macro is causing the host compiler to elide the CUDA kernels because it thinks they are unused. It requires quite a few workarounds to get this right -- CUB should probably perform these on behalf of the client.

**Comment by dumerrill** [comment]
>> the CUB_CDP macro is causing the host compiler to elide the CUDA kernels because it thinks they are unused.

Actually, your program's #ifdef on line 20 is causing the compiler to elide the CUDA kernels.  Take that out and call CUB.  It will return cudaErrorNotSupported if it's not supported.  Don't use it on some compiler passes and not others.

**Comment by jaredhoberock** [comment]
The `ifdef` is integral to another, larger, codebase this snippet is part of a larger codebase, this snippet is taken from. The code needs to choose statically, at comiple time, how to implement a sort. It's not possible to call CUB if CUDA dynamic parallelism is not supported, correct? When CUDA dynamic parallelism is supported, it will use CUB. If not, the code will do something else. Is it possible to build a program like that using CUB? One way  seems to be the workaround I mentioned.

Why not implement the workaround within CUB so that users don't have to do it themselves? It leads to difficult to debug errors, otherwise.

**Comment by dumerrill** [comment]
>> It's not possible to call CUB if CUDA dynamic parallelism is not
supported, correct?


Not only is it possible, it's required, actually.  CUB simply returns
cudaErrorNotSupported when used in device code.  (You don't need to do that
yourself.)

To elaborate, CUB itself uses an #ifdef internally in the same manner.
However, it instantiates its kernels before its #ifdef in order to make
sure the kernels get compiled on all passes regardless.  If the calling
application places an #ifdef around cub for some compiler passes (as in
your example), then you risk kernels not being compiled for sm10..sm30.

The same is true for any kernel call, e.g.:

    __host__ __device__ void CdpFoo()
    {
    #if !defined(__CUDA_ARCH__) || (__CUDA_ARCH__>= 350 &&
defined(__CUDACC_RDC__))
      FooKernel<<<...>>>(...);
    #endif
    }

    int main()
    {
        CdpFoo();
        return 0;
    }


In this case, SomeKernel will not be compiled at all with nvcc -arch=sm_20.

**Comment by dumerrill** [comment]
For reference, another way to protect dispatch (yet force compilation) is
simply to create a kernel function pointer, but don't invoke it on certain
code paths.  This is much less verbose.

*template* <*typename* *T*>

__global__ *void* *FooKernel*(*T** d_in) {}



*template* <*typename* *T*>

__host__ __device__ cudaError_t *foo_wrapper*(*T** d_in)

{

    *void* (*kernel_ptr)(*T**) = FooKernel<*T*>;



*#if* !defined(__CUDA_ARCH__) || (__CUDA_ARCH__>= 350 &&
defined(__CUDACC_RDC__))

    kernel_ptr<<<1,1>>>(d_in);

    *return* *cudaPeekAtLastError*();

*#else*

    *return* cudaErrorNotSupported;

*#endif*

};
