### ISSUE TITLE
Compilation fails : 'cub::DispatchRadixSort<false,KeyT,ValueT,int>' : assignment operator could not be generated

### ISSUE THREAD

**Issue by sarvex** [NVlabs/cub#38]
While building CNTK, warnings are treated as error and because of this warning compilation fails

`'cub::DispatchRadixSort<false,KeyT,ValueT,int>' : assignment operator could not be generated`

Now a temporary workaround is to disable the "warnings as error switch in CNTK", but a better solution would be to eliminate this warning in CUB

**Comment by dumerrill** [comment]
Can you provide the full warning output (call-stack, line numbers, template parameters, etc.)?  That way I can hunt it down and remedy the warning.  Thanks!

**Comment by sarvex** [comment]
File :  cub/cub/device/dispatch/dispatch_radix_sort.cuh : 679
Definition of DispatchRadixSort could not generate the assignment operator. 

The same can be easily reproduced in Visual Studio by setting "Treat Warnings as error"

**Comment by dumerrill** [comment]
Please give me some instructions for obtaining/building your project.  Or a small repro.  Thanks!

**Comment by sarvex** [comment]
I am trying to build Microsoft CNTK (https://github.com/Microsoft/CNTK). The setup instruction are specified in detail at https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows. 

I was trying to build the CNTK project on Windows 10 machine with Visual Studio 2013

**Comment by dumerrill** [comment]
closing for lack of feedback.
