### ISSUE TITLE
In kernel float cub::BlockRadixSort crashes

### ISSUE THREAD

**Issue by fusr** [NVlabs/cub#39]
I'm having issues with using radix sort in kernel for float sorting.

Attached example code with output and cuda-memcheck summary. The cub version is 1.5.1.

[source.txt](https://github.com/NVlabs/cub/files/171083/source.txt)

[output_with_sort_called.txt](https://github.com/NVlabs/cub/files/171084/output_with_sort_called.txt)

[output_with_sort_commented_out.txt](https://github.com/NVlabs/cub/files/171085/output_with_sort_commented_out.txt)

[cuda-memcheck.txt](https://github.com/NVlabs/cub/files/171086/cuda-memcheck.txt)

**Comment by dumerrill** [comment]
The problem is that you are specifying 128 (DATA_MAX_SIZE) as the number of threads when specializing the block-sorting class, but your block size is actually only 32 threads (BLOCK_SIZE).  Use

    typedef cub::BlockRadixSort< float, BLOCK_SIZE, ELEMENT_PER_THREAD > BlockRadixSort;

instead of 

    typedef cub::BlockRadixSort< float, DATA_MAX_SIZE, ELEMENT_PER_THREAD > BlockRadixSort;

Hope that helps, 

Duane
