### ISSUE TITLE
cub::DeviceRadixSort::SortPairs for multiple values

### ISSUE THREAD

**Issue by kaatish** [NVlabs/cub#40]
I have three vectors
```
thrust::device_vector<unsigned long> keys(N);
thrust::device_vector<unsigned> value1(N);
thrust::device_vector<unsigned> value2(N);
```

I am trying to achieve the equivalent of `thrust::sort_by_key` using cub::DeviceRadixSort::SortPairs.

```
thrust::sort_by_key(keys.begin(), keys.end(),
    thrust::make_zip_iterator(thrust::tuple(value1.begin(), value2.begin())));
```

So essentially, my question is, how do I sort by key where each key has multiple values associated to it?

**Comment by sh1ng** [comment]
@kaatish have you found a solution for than?

**Comment by kaatish** [comment]
Unfortunately I have not.
