### ISSUE TITLE
Retaining zips of previous branches/versions

### ISSUE THREAD

**Issue by sjperkins** [NVlabs/cub#41]
I noticed that the 1.5.1 branch was removed, along with the cub.1.5.1.zip file when 1.5.2 was released. Would it be possible to retain archives of these older versions so that builds can be reproducible? In my case, I had a 1.5.1 dependency in a Dockerfile. This isn't a train smash for me by any means, but it'd be nice to have some future-proofing.

**Comment by dumerrill** [comment]
Sorry for the inconvenience.  We'll be using tags for all releases moving forward (to supplement the major.minor.last branches, which we keep around for hotfixes for customers)
