### ISSUE TITLE
RFEs for  cub::DeviceScan::ExclusiveScan

### ISSUE THREAD

**Issue by egaburov** [NVlabs/cub#48]
1. Add API that also accepts`init` value and constructs an exclusive scan with the following semantics:`output[0] = init`, `output[i>0] = init  ⊕  input[0] ⊕ ... ⊕ input[i-1]`

2. Add API that doesn't require `identity` value for an user-provided reduction operator. If user doesn't know, or doesn't want to provide one, exclusive scan, similar to inclusive scan, should just work. If this is less efficient, that's okay and its user's choice to have faster implementation by providing the `identity`value.

**Comment by egaburov** [comment]
not required anymore. closing RFE.

**Comment by dtrebbien** [comment]
This appears to have been implemented in 618477c9.
