### ISSUE TITLE
RFE: cub::BlockScan  : different type for input and output data, as well as scan operator

### ISSUE THREAD

**Issue by egaburov** [NVlabs/cub#49]
1. Allow both inclusive and exclusive sum have different types for input and output. For example, input type is float, output type is integer. Sum is done as float, but result is stored as int.

2. Allow scan operator to have different type than that of input or output types  [1].  For example, if input type is "float", output type is "int", and scan operator has signature "double operator()(double,double)", the final result of the scan is of type "double" but stored as "int". This will help to avoid precision loss during scan operation in some cases.

http://en.cppreference.com/w/cpp/algorithm/exclusive_scan

**Comment by egaburov** [comment]
not required anymore. closing RFE.

**Comment by VladimirOvsyannikovEvision** [comment]
I can't compile my code that uses DeviceScan if input type is float and out is double. Is it relevant?

**Comment by sh1ng** [comment]
I can't compile my code that uses DeviceScan if input type is float and out is double. Is it relevant?
