### ISSUE TITLE
Numerical stability issues with block load & store using ITEMS_PER_THREAD = 1

### ISSUE THREAD

**Issue by dtrebbien** [NVlabs/cub#51]
There appear to be numerical stability issues when I use `cub::BlockLoad`/`cub::BlockStore` with ITEMS_PER_THREAD = 1. Using ITEMS_PER_THREAD = 2 or more is okay.

Steps to reproduce:

 0. Install Boost. (I am on Mac, and I installed Boost via the Homebrew bottle: `brew install boost`)
 1. Save the attached [`test.cu`](https://github.com/NVlabs/cub/files/409603/test.cu.txt) and [`Makefile`](https://github.com/NVlabs/cub/files/409602/Makefile.txt) to a new directory. This test case computes a [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) `C <- alpha * A (*) B + beta * C` via a "basic" kernel (`basicHadKernel`) and one using CUB (`cubHadKernel`).
 2. Edit `Makefile` to change the include path to CUB.
 3. Run `make && ./test`. You should see:

        Running 1 test case...
        
        *** No errors detected

 4. Change line 38 of `test.cu` to:

    ```c++
    static constexpr int ITEMS_PER_THREAD = 1;
    ```

 5. Run `make && ./test`. You should now see something like:

        Running 1 test case...
        test.cu:279: error: in "test_had": difference{1.43188e-05} between C2[i]{-0.00731719984} and expected[i]{-0.00731730461} exceeds 0.001%
        test.cu:279: error: in "test_had": difference{0.000314992} between C2[i]{0.000154208246} and expected[i]{0.000154256821} exceeds 0.001%
        test.cu:279: error: in "test_had": difference{1.46731e-05} between C2[i]{0.0272928048} and expected[i]{0.0272932053} exceeds 0.001%
        [... output clipped ...]

        *** 333 failures are detected in the test module "tests"

    As you can see, many values now exceed the tolerance threshold.

**Comment by dtrebbien** [comment]
Sorry for this report. It is not actually a problem in CUB; the compiler is emitting different code. For the "basic" kernel, the compiler emits two `mul.f32` instructions to calculate `A[i] * alpha` and `(A[i] * alpha) * B[i]`, followed by an `fma.rn.f32` instruction to calculate `C[i] * beta + ((A[i] * alpha) * B[i])`. For the other kernel using CUB, the compiler emits two `mul.f32` instructions to calculate `A[i] * alpha` and `C[i] * beta`, followed by an `fma.rn.f32` instruction to calculate `((A[i] * alpha) * B[i] + (C[i] * beta)`.

**Comment by egaburov** [comment]
I can reproduce this error with CUDA 7.5, but it is gone in CUDA 8.0rc.
