### ISSUE TITLE
Infinite loop in cub::CachingDeviceAllocator::NearestPowerOf

### ISSUE THREAD

**Issue by drnikolaev** [NVlabs/cub#54]
It happens for sizes between 2^63 and 2^64-1

**Comment by dumerrill** [comment]
Thanks; fixed in 

commit 0fa304f28fb3f6b3309b339e88dae6fcb02c6a35
Author: dumerrill <dumerrill@DUMERRILL-DT3.nvidia.com> 2016-09-07 17:33:21
Committer: dumerrill <dumerrill@DUMERRILL-DT3.nvidia.com> 2016-09-07 17:33:21
