### ISSUE TITLE
DeviceScan::ExclusiveSum blocks execution thread

### ISSUE THREAD

**Issue by sh1ng** [NVlabs/cub#57]
Found it out with nvidia visual profiler

```
void *d_temp_storage = NULL;
                              size_t temp_storage_bytes = 0;
                              CubDebugExit(cub::DeviceScan::ExclusiveSum(d_temp_storage,
                                                                    temp_storage_bytes,
                                                                    d_in,
                                                                    d_out,
                                                                    count,
                                                                    s));

                              CubDebugExit(g_allocator.DeviceAllocate(&d_temp_storage, temp_storage_bytes, s));

                              CubDebugExit(cub::DeviceScan::ExclusiveSum(d_temp_storage,
                                                                    temp_storage_bytes,
                                                                    d_in,
                                                                    d_out,
                                                                    count,
                                                                    s));

asynchronous cuda 
```

**Comment by sh1ng** [comment]
Example
https://github.com/sh1ng/thrust_async/blob/master/example_device_scan.cu

that code compiled with 

> nvcc -gencode arch=compute_61,code=sm_61 --default-stream=per-thread  example_device_scan.cu -o a -I../cub/ -O3

**Comment by dumerrill** [comment]
There are no blocking API calls in device-scan.  How is your Visual Profiler indicating that it blocks the CPU thread?  (Be sure to check the "profile execution on CPU" checkbox when configuring the session's profiling options.)

When I compile that program using your string, run it through the Visual profiler, I see the following timeline, which shows kernel execution overlapping with the CPU's subsequent call to cudaStreamSynchronize() at the end of the program.

![image](https://cloud.githubusercontent.com/assets/1476032/19210214/db288202-8ce9-11e6-8fcd-a18595ed5260.png)

Let me know if I'm missing anything,

Duane

**Comment by sh1ng** [comment]
I've seen the similar picture. But why kernels don't overlap(or overlap just a little)?

**Comment by dumerrill** [comment]
They do overlap eachother by a little in this pic, and certainly they overlap the host.  

TBH, overlapping is bad in this case.  Each scan is large enough to fill the GPU by itself -- if the scheduler overlapped them more, then overall performance would go down because they would be contending for hardware resources (like L2 cache thrashing).
