### ISSUE TITLE
Does cub::DeviceRadixSort support that the input and the output is the same pointer?

### ISSUE THREAD

**Issue by desert0616** [NVlabs/cub#60]
Hi, 
I was wondering whether it is ok if I set the input and the output to the same pointer? It is usual to sort an array and output the sorted results to the original location.

Thanks.

**Comment by dumerrill** [comment]
Not yet.  We will soon.

**Comment by desert0616** [comment]
Does "not yet" means any overlapped input and output used for cub device functions will get an incorrect result?

Thanks

**Comment by dumerrill** [comment]
Yeah, there is potential for incorrect results (depending on the number of
internal sorting passes, e.g., if it is an odd number, the results would
end up in the temporary buffer.)

**Comment by desert0616** [comment]
Thank you so much for the reply .Dose the DoubleBuffer version api can avoid this issue?
