### ISSUE TITLE
cub::DeviceRadixSort::SortPairs for multiple values

### ISSUE THREAD

**Issue by sh1ng** [NVlabs/cub#61]
Sorry for a duplicate(https://github.com/NVlabs/cub/issues/40) but it's been closed without fix or workaround. 

Suppose I've three arrays/vectors

- keys
- values1
- values2

and I want to sort values1 and values2 by keys.
It can be done by calling SortPairs twice.

Can the running time be improved by putting them in a single sort?
Can you provide a code snippet  to do that or implementation require?

**Comment by dumerrill** [comment]
You could zip values1 and values2 into a single tuple-array (array-of-structures) and then do a single key-value sort.  Or you could create a index array (the natural numbers), sort that as the paired values, and then use it as a permutation map to reorder any number of other arrays in a simple gather-scatter kernel.
