### ISSUE TITLE
cub::TilePrefixCallbackOp::WarpReduce doesn't permit ptx arch specialization

### ISSUE THREAD

**Issue by egaburov** [NVlabs/cub#68]
`cub::TilePrefixCallbackOp` should also accept ptx arch as its template argument, to specialise `WarpReduce<T>` (https://github.com/NVlabs/cub/blob/1.5.5/cub/agent/single_pass_scan_operators.cuh#L658)

**Comment by dumerrill** [comment]
Fixed in the above commit for v1.6.3
