### ISSUE TITLE
KeyVairPair won't work if Key has non-trivial ctor

### ISSUE THREAD

**Issue by egaburov** [NVlabs/cub#71]
https://github.com/NVlabs/cub/blob/1.5.5/cub/util_type.cuh#L651

Is union still necessary, if so is there other way to enforce alignment ?

**Comment by dumerrill** [comment]
Curious... are you are using KeyValuePair type for your own purposes?  

That union is for alignment purposes on the host pass only -- it isn't defined for device passes, where the size of a long is always the same.  And CUB's host-side API stubs don't use that type in a way that would result in instantiation with a non-trivialy-constructable key type.

**Comment by dumerrill** [comment]
Fixed in the above three commits for v1.6.3
