### ISSUE TITLE
cub:InequalityWrapper::operator() should be non-const 

### ISSUE THREAD

**Issue by egaburov** [NVlabs/cub#72]
https://github.com/NVlabs/cub/blob/1.5.5/cub/thread/thread_operators.cuh#L99

If EqualityOp is a non-const callable, InequalityWrapper::operator() produces in compilation error. non-const will work with both non-const and const EqualityOp::operator()

**Comment by dumerrill** [comment]
Fixed in the above commit for v1.6.3
