### ISSUE TITLE
Can't sum float2 into double2

### ISSUE THREAD

**Issue by sh1ng** [NVlabs/cub#75]
Hi,

thanks you for fixing https://github.com/NVlabs/cub/issues/59

Now I'm trying to sum float2 into double2 and getting error
```

_cub/cub/block/block_load.cuh(85): error: no operator "=" matches these operands
            operand types are: double2 = float2
```

**Comment by egaburov** [comment]
I don't think this is is not  CUB error. In CUDA you will get the similar error when attempting to assign float2 to double2.

**Comment by sh1ng** [comment]
But might be you can suggest a workaround. Or add overload for Scan function with additional function to extend assignment

**Comment by egaburov** [comment]
User has the responsibility to ensure that types are convertible from one to another, library just does the assignment. Consider creating a simple derived class to extend the functionality of the base one, e.g.:

```
$ cat r.cu
struct mydouble2 : double2
{
  __device__ mydouble2(double2 other) : double2(other) {}
  __device__ mydouble2(float2 other) : double2(make_double2(other.x,other.y)) {}
};
__global__ void k()
{
  float2 a = {4,2};
  mydouble2 b = a;
  double2 c = b;
}
$ nvcc -c r.cu
$
```

**Comment by sh1ng** [comment]
thanks
