### ISSUE TITLE
cub::NumericTraits has no methods "Lowest", "Max"

### ISSUE THREAD

**Issue by idofr** [NVlabs/cub#76]
When trying to compile the reduction example, the following error message overflows the stack. They all look like:

../../test/test_util.h(987): error: class "cub::NumericTraits<long long>" has no member "Lowest"

**Comment by dumerrill** [comment]
Can you provide the compiler commandline you're invoking?  

Which reduction example?  I can't reproduce a problem with either...

`$nvcc -arch=sm_XX example_device_reduce.cu -I../.. -lcudart -O3`

and 

`nvcc -arch=sm_35 example_block_reduce.cu -I../.. -lcudart -O3`

compile fine for me on both windows and linux.

**Comment by dumerrill** [comment]
Closing for lack of feedback.
