### ISSUE TITLE
CUB versioning

### ISSUE THREAD

**Issue by RAMitchell** [NVlabs/cub#77]
I have introduced CUB 1.5 as a dependency to my project here:
https://github.com/RAMitchell/xgboost/tree/master/plugin/updater_gpu

I have noticed that API breaking changes have been introduced in 1.6. Download links from the "stable releases" section however at http://nvlabs.github.io/cub/index.html all link to 1.6.

This makes it very hard to distribute my algorithm if my users can only get the newest version with a different API.

**Comment by dumerrill** [comment]
I'll fix the links on the docs page, thanks for pointing it out.

You can get the branches on on the [GibHub page](https://github.com/NVlabs/cub), simply select the branch you want from the drop-down:

![image](https://cloud.githubusercontent.com/assets/1476032/21014988/24180680-bd2e-11e6-9899-4e1d150f1a8d.png)

**Comment by dumerrill** [comment]
We'll be using GIT tags moving forward to demarcate releases (as well as keeping the last major.minor.last branches for customer hotfixes)
