### ISSUE TITLE
Do you have any kind of Null iterator/discard iterator

### ISSUE THREAD

**Issue by sh1ng** [NVlabs/cub#79]
Suppose I need to sort pairs but I don't care about sorted keys.
Is it possible to discard sorted key result? 
It will reduce memory footprint that might be very useful sometimes.

**Comment by dumerrill** [comment]
We do have a discard iterator:
https://github.com/NVlabs/cub/blob/1.6.4/cub/iterator/discard_output_iterator.cuh

But I don't think it will do you any favors here.  Radix sorting works in
passes, typically 5-7 passes for 32-bit keys.  You would only be able to
discard them on the very last pass, so any performance improvement from
removing only a quarter of the last pass' I/O overhead would be marginal at
best, I would say.

**Comment by sh1ng** [comment]
Look like RadixSort only supports pointer as an input. Could you give an example how to use it with iterator?

**Comment by dumerrill** [comment]
>> Could you give an example how to use it with iterator?


There isn't a way to use iterators.  Radix sorting works in passes; need to
read in the input several times.  So we can't really take a custom input
iterator that might transform the input -- it's not useful for any passes
other than the first.  (And you'd still have to provide two regular
pointers for the other passes.)
