### ISSUE TITLE
WarpScan requires __syncthreads before temp_storage to be reused??

### ISSUE THREAD

**Issue by guowentian** [NVlabs/cub#85]
Hi, I used cub::WarpScan to get exclusiveSum inside a warp. I am curious why we need to call __syncthreads before temp_storage to be reused , as specified in the following website? 
https://nvlabs.github.io/cub/classcub_1_1_warp_scan.html#a2b724675bca864957538440cffc95f4e
The reason that we use WarpScan is that we dislike synchronization between warps and make different warps work independently. However, if a warp needs to call WarpScan multiple times, it needs to synchronize with other warps. In that sense, WarpScan seems useless and cannot help different warps work independently.

**Comment by dumerrill** [comment]
>> The reason that we use WarpScan is that we dislike synchronization between warps

I think you mean no "synchronization _within_ warps".  You will always need synchronization to communicate _between_ warps.

For warp-wide operations like WarpReduce and WarpScan, you don't need to call __syncthreads() before having the warp _re-enter_ the primitive.  If you are going to _reuse_ the storage (i.e., alias it or repurpose it for some storage, perhaps in a union with a BlockXYZ primtive), then you should synchronize after invoking it to make sure all the warp threads are out of it.
