### ISSUE TITLE
example_device_radix_sort.cu generate an error(compute_50,sm_50;compute_52,sm_52)

### ISSUE THREAD

**Issue by zzf123000** [NVlabs/cub#90]
example_device_radix_sort.cu generate an error(compute_50,sm_50;compute_52,sm_52)

Compile cub-1.7.0 (cub-1.6.4) \ examples \ device \ example_device_radix_sort.cu, generate an error:
G:\develop_kit\cub-1.7.0\cub-1.7.0\examples\device\example_device_radix_sort\example_device_radix_sort>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_50,code=\"sm_50,compute_50\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\x86_amd64"  -I"G:\develop_kit\cub-1.7.0\cub-1.7.0" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o x64\Release\example_device_radix_sort.cu.obj "G:\develop_kit\cub-1.7.0\cub-1.7.0\examples\device\example_device_radix_sort.cu"
1>example_device_radix_sort.cu
1>CUDACOMPILE : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets(689,9): error MSB3722: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_50,code=\"sm_50,compute_50\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\x86_amd64"  -I"G:\develop_kit\cub-1.7.0\cub-1.7.0" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o x64\Release\example_device_radix_sort.cu.obj "G:\develop_kit\cub-1.7.0\cub-1.7.0\examples\device\example_device_radix_sort.cu"”已退出，返回代码为 5。请验证您是否拥有运行此命令的足够权限。
1>已完成生成项目“example_device_radix_sort.vcxproj”的操作 - 失败。

My computer configuration is: Windows10 +GPU(gtx 970 maxwell Compute Capability 5.2 )  + CUDA 8.064 + Visual Studio 2015 

Will VS2015 -> CUDA C / C ++ -> Device -> Code Generation: compute_50, sm_50
Changed to Code Generation: compute_35, sm_35, compiled through.

Based on the above error and set the experimental analysis, the resulting estimate is derived from cub \ device \ dispatch \ dispatch_radix_sort.cuh: 443
Template
    Typename KeyT, /// <Key type
    Typename ValueT, /// <Value type
    Typename OffsetT> /// <Signed integer type for global offsets
Struct DeviceRadixSortPolicy
{
631:
    Struct Policy500: ChainedPolicy <500, Policy500, Policy350>
    {
        Enum {
            PRIMARY_RADIX_BITS = 7, // 3.5B 32b keys / s, 1.92B 32b pairs / s (TitanX)
            SINGLE_TILE_RADIX_BITS = 6,
            SEGMENTED_RADIX_BITS = 6, // 3.1B 32b segmented keys / s (TitanX)
        };

        // ScanPolicy
        Typedef AgentScanPolicy <512, 23, BLOCK_LOAD_WARP_TRANSPOSE, LOAD_DEFAULT, BLOCK_STORE_WARP_TRANSPOSE, BLOCK_SCAN_RAKING_MEMOIZE> ScanPolicy;

        // Downsweep policies
        Typedef AgentRadixSortDownsweepPolicy <160, CUB_MAX (1, ​​39 / SCALE_FACTOR_4B), BLOCK_LOAD_WARP_TRANSPOSE, LOAD_DEFAULT, false, BLOCK_SCAN_WARP_SCANS, RADIX_SORT_SCATTER_TWO_PHASE, PRIMARY_RADIX_BITS> DownsweepPolicy;
        Typedef AgentRadixSortDownsweepPolicy <256, CUB_MAX (1, ​​16 / SCALE_FACTOR_4B), BLOCK_LOAD_DIRECT, LOAD_LDG, true, BLOCK_SCAN_RAKING_MEMOIZE, RADIX_SORT_SCATTER_TWO_PHASE, PRIMARY_RADIX_BITS - 1> AltDownsweepPolicy;

        // Upsweep policies
        Typedef DownsweepPolicy UpsweepPolicy;
        Typedef AltDownsweepPolicy AltUpsweepPolicy;

        // Single-tile policy
        Typedef AgentRadixSortDownsweepPolicy <256, CUB_MAX (1, ​​19 / SCALE_FACTOR_4B), BLOCK_LOAD_DIRECT, LOAD_LDG, true, BLOCK_SCAN_WARP_SCANS, RADIX_SORT_SCATTER_TWO_PHASE, SINGLE_TILE_RADIX_BITS> SingleTilePolicy;

        // Segmented policies
        Typedef AgentRadixSortDownsweepPolicy <192, CUB_MAX (1, ​​31 / SCALE_FACTOR_4B), BLOCK_LOAD_WARP_TRANSPOSE, LOAD_DEFAULT, true, BLOCK_SCAN_WARP_SCANS, RADIX_SORT_SCATTER_TWO_PHASE, SEGMENTED_RADIX_BITS> SegmentedPolicy;
        Typedef AgentRadixSortDownsweepPolicy <256, CUB_MAX (1, ​​11 / SCALE_FACTOR_4B), BLOCK_LOAD_WARP_TRANSPOSE, LOAD_DEFAULT, true, BLOCK_SCAN_WARP_SCANS, RADIX_SORT_SCATTER_TWO_PHASE, SEGMENTED_RADIX_BITS - 1> AltSegmentedPolicy;
    };

}

Segmented keys / s (TitanX)

The struct Policy500, only for the implementation of TitanX? Why not? Gtx 970 maxwell Compute Capability 5.2

**Comment by zzf123000** [comment]
This question is caused by compiling the CNTK project under the MathCUDA -> GPUMatrix.cu file.

**Comment by zzf123000** [comment]
In fact, set C / C + + CUDA -> Code Generation: compute_35, sm_35, will be able to successfully generated. How can I set the Code Generation: compute_50, sm_50; compute_52, sm_52 configuration can also succeed in the gtx 970 maxwell Compute Capability 5.2?

**Comment by dumerrill** [comment]
I'm afraid this is a known compiler bug in Toolkit 8.0.6x.  Alternatives include:

- Clone (or rebase) CUB `master` branch (or upcoming v1.7.1, when snapped), which has a work-around for CUDA 8.0.6x
- Use [the newer CUDA Toolkit 9.x](https://developer.nvidia.com/cuda-toolkit/whatsnew) (currently in RC), which addresses the issue
- Use [the older CUDA Toolkit 8.0.44 available in the archives](https://developer.nvidia.com/cuda-80-download-archive), the delta from 8.0.6x mostly being performance of libraries (CUBLAS, CUDNN, etc.)
