### ISSUE TITLE
DeviceRadix::SortPairs compilation error for SM 5.0 / SM 5.2

### ISSUE THREAD

**Issue by ptheywood** [NVlabs/cub#91]
Under windows building `test/ for `SM50` and `SM52` with `CUDA 8.0.61`

This occurs for atleast CUB 1.7.0 and CUB 1.6.4.

To reproduce, on a window 10 system with Visual Studio 2015:

1. Download `CUB 1.7.0` (or `CUB 1.6.4`)
2. `cd cub-1.7.0/test`
3. ` export sm=500` or ` export sm=520`
4. `make test_device_radix_sort`

Output produced:

```
mkdir -p bin
"/c/program files/nvidia gpu computing toolkit/cuda/v8.0/bin/nvcc" -DTEST_ARCH=5                                                                             20  -gencode=arch=compute_52,code=\"sm_52,compute_52\"  -o bin/test_device_radix                                                                             _sort_sm520_nvvm_8.0_abi_nocdp_x86_64_thorough test_device_radix_sort.cu -DSM520                                                                              -Xptxas -v -Xcudafe -#  -Xcompiler -ffloat-store -m64 -I../ -I../test   -O3
cl : Command line warning D9002 : ignoring unknown option '-ffloat-store'
test_device_radix_sort.cu
Front end time                      11.04 (CPU)      11.00 (elapsed)
Back end time                        3.96 (CPU)       4.00 (elapsed)
Total compilation time              16.97 (CPU)      17.00 (elapsed)
cl : Command line warning D9002 : ignoring unknown option '-ffloat-store'
test_device_radix_sort.cu
Front end time                       1.84 (CPU)       2.00 (elapsed)
Back end time                        0.36 (CPU)       1.00 (elapsed)
Total compilation time               2.27 (CPU)       3.00 (elapsed)
cl : Command line warning D9002 : ignoring unknown option '-ffloat-store'
tmpxft_00005514_00000000-8_test_device_radix_sort.cudafe1.gpu
Front end time                      11.18 (CPU)      11.00 (elapsed)
Back end time                        3.58 (CPU)       4.00 (elapsed)
Total compilation time              14.92 (CPU)      15.00 (elapsed)
cl : Command line warning D9002 : ignoring unknown option '-ffloat-store'
tmpxft_00005514_00000000-22_test_device_radix_sort.cudafe2.gpu
test_device_radix_sort.cu
nvcc error   : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
make: *** [bin/test_device_radix_sort_sm520_nvvm_8.0_abi_nocdp_x86_64_thorough]                                                                              Error 5
```

This compiles fine for both `SM35` and `SM61`.

~~I will also submit this to the Nvidia bug tracker as a compiler issue.~~

I am unable to submit nvidia bug reports currently with the following error

>An error occurred while processing your request.

I have reproduced this issue on a second Windows 10 PC with CUDA 8.0.61

I have also confirmed 

+ this does **NOT** effect CUB `1.5.2`
+ this does **NOT** effect `CUDA 8.0.44`, making this most likely a compiler bug.

**Comment by dumerrill** [comment]
I'm afraid this is a known compiler bug in Toolkit 8.0.6x.  Alternatives include:

- Clone (or rebase) CUB `master` branch (or upcoming v1.7.1, when snapped), which has a work-around for CUDA 8.0.6x
- Use [the newer CUDA Toolkit 9.x](https://developer.nvidia.com/cuda-toolkit/whatsnew) (currently in RC), which addresses the issue
- Use [the older CUDA Toolkit 8.0.44 available in the archives](https://developer.nvidia.com/cuda-80-download-archive), the delta from 8.0.6x mostly being performance of libraries (CUBLAS, CUDNN, etc.)
