### ISSUE TITLE
Git clone size

### ISSUE THREAD

**Issue by RAMitchell** [NVlabs/cub#94]
A git clone of the cub repo is about 145mb.

We are using cub as a submodule in https://github.com/dmlc/xgboost, but the size of the repo has been problematic.

I have looked at alternative approaches such as shallow submodules or git subtrees but these come with problems of their own. Would you consider addressing the problem from this end?

**Comment by dumerrill** [comment]
Certainly.  I cleaned up old zombie files (binaries, test data, etc.) no longer in the repo.  

A shallow clone of only one release branch is now only a couple hundred kilobytes:

`dumerrill@MoochBot MINGW64 /d/Dev/workspace
$ git clone -b 1.7.0 --single-branch https://github.com/NVlabs/cub.git --depth 1
Cloning into 'cub'...
remote: Counting objects: 180, done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 180 (delta 53), reused 52 (delta 13), pack-reused 0
Receiving objects: 100% (180/180), 489.53 KiB | 2.06 MiB/s, done.
Resolving deltas: 100% (53/53), done.`

and a full clone is only a few megabytes:

`dumerrill@MoochBot MINGW64 /d/Dev/workspace
$ git clone https://github.com/NVlabs/cub.git
Cloning into 'cub'...
remote: Counting objects: 31243, done.
remote: Compressing objects: 100% (2656/2656), done.
remote: Total 31243 (delta 9221), reused 9321 (delta 7667), pack-reused 20327
Receiving objects: 100% (31243/31243), 19.84 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (28114/28114), done.
`

**Comment by RAMitchell** [comment]
Did you accidentally remove block/block_scan.cuh?

**Comment by dumerrill** [comment]
Yes, it was a tragic casualty of purging trash from the history.  (Only the [tip commit of the master HEAD at the time](https://github.com/NVlabs/cub/tree/e5dc139f50931b7809f02c97b07abd7eed9e3881 was protected from the large-file cleaning, and so block_scan.cuh was culled release branches (and tags, if we had them).    I normally abhor changes to a release, but in this case it seemed prudent to replace the file in each release branch with its proper version.  

So.... repo size is way down.  But open clones might need to be rebased, and some hashes for repo's fetched from branch URLs won't match what they used to.

**Comment by RAMitchell** [comment]
We updated the submodule reference and everything works fine. Appreciate you taking the time to do this.
