### ISSUE TITLE
Thousands of errors returned by visual studio intellisense

### ISSUE THREAD

**Issue by Patryk-B** [NVlabs/cub#96]
Whenever I include "cub/cub.cuh" file to my application's source code, I get the following visual studio's IntelliSense behaviour:

![screenshot](https://user-images.githubusercontent.com/23104132/27995238-053ab948-64cb-11e7-849f-0d16cc46bc46.jpg)

In the attached screenshot, you are able to see 5362 error's reported by IntelliSense while the source code is a blank `main()` function.

What can I do to fix this issue?

**Comment by Patryk-B** [comment]
I found a solution to this problem. 

`#ifndef __INTELLISENSE__

#include <cub/cub.cuh>

// And other troublesome libraries or code-blocks....

#endif`

The Visual Studio's __INTELLISENSE__ macro is only defined when Visual Studio itself parses the file, not during compilation. Therefore anything inside a code block above will not be checked by IntelliSense algorithms.

**Comment by Patryk-B** [comment]
I have found a solution to this problem.
This problem is caused by IntelliSense not being able to correctly parse `cuda device side code`. 

End user can fix this by simply wrapping `#include <cub/cub.cuh>` with `#ifndef __INTELLISENSE__` guard.

**Comment by dumerrill** [comment]
Hi Patryk, I'm closing this issue.  (FWIW, for Eclipse C++, which is what I use on both windows/linux as my IDE, I've had to edit the project file to define keywords like __device__ and __global__ as "" in order to mollify syntax checker.)
