### ISSUE TITLE
1.6.4 -> 1.7.0 breaking changes or bugs

### ISSUE THREAD

**Issue by sh1ng** [NVlabs/cub#97]
After update to a new version I've noticed changes in the results(I have a few test with pre-computed 100% valid results). I'm using sort and prefix sum. 
Do you have any breaking changes in version 1.7 that should be taken into account?
I'm going to create a few simple test to localize the issue and give more details.

cuda 8.0
linux with gcc-5+
sm = 610

**Comment by dumerrill** [comment]
Unless your prefix sum is pseudo-associative (e.g., prefix sum over floating point numbers), sorting and scan should be stable and deterministic regardless of parallelization.  Please let me know if you can construct a small reproducer.

Thanks,

Duane

**Comment by sh1ng** [comment]
version 1.7.3 works ok
