### ISSUE TITLE
"#include cub/device/device_radix_sort.cuh" crashes NVCC on Windows 10 for compute_52,sm_52;compute_61,sm_61

### ISSUE THREAD

**Issue by gooze74** [NVlabs/cub#99]
I've successfully using "cub::DeviceRadixSort::SortPairsDescending" with Visual Studio 2013 in 64 bits and CUDA 8 on Windows 7, Windows Server 2012 R2 but **not on Windows 10**. The CUDA installer is different on Windows 10 platform and has version 8.0.61 instead of 8.0.44 at the creation of this issue.
If I remove this call, compilation is always successful.

`1>------ Build started: Project: VisCuda, Configuration: Debug x64 ------
1>  Compiling CUDA source file modules\viscuda\ocv_kernel_ext.cu...
1>  
1>  C:\bsa_0736_3380_iQ500\branch\8.3\vision>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env --cl-version 2013 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64"  -Iinclude\VisCuda -Iinclude\logger -Iinclude\memory -I"C:\Program Files\Matrox Imaging\Mil\DLL\..\include" -Iinclude\visutils -I3rdparty\opencv\include -I3rdparty\cub -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -o bin\x64\Debug\VisCuda\ocv_kernel_ext.cu.obj 
1>  ocv_kernel_ext.cu
1>CUDACOMPILE : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 8.0.targets(689,9): error MSB3722: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env --cl-version 2013 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64"  -Iinclude\VisCuda -Iinclude\logger -Iinclude\memory -I"C:\Program Files\Matrox Imaging\Mil\DLL\..\include" -Iinclude\visutils -I3rdparty\opencv\include -I3rdparty\cub -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -o bin\x64\Debug\VisCuda\ocv_kernel_ext.cu.obj "C:\bsa_0736_3380_iQ500\branch\8.3\vision\modules\viscuda\ocv_kernel_ext.cu"" exited with code 5. Please verify that you have sufficient rights to run this command.
`

**Comment by dumerrill** [comment]
What happens if you omit the "-g" flag from the nvcc compile string?  (I have seen the trampolines that get inserted in debug mode sometimes cause ptxas/cicc issues.)

**Comment by gooze74** [comment]
Thank you for your reply. I still get the same compiler crash.

1>------ Build started: Project: VisCuda, Configuration: Release x64 ------
1>  Compiling CUDA source file modules\viscuda\ocv_kernel_ext.cu...
1>  
1>  C:\bsa_0736_3380_iQ500\branch\8.3\vision>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env --cl-version 2013 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64"  -Iinclude\VisCuda -Iinclude\logger -Iinclude\memory -I"C:\Program Files\Matrox Imaging\Mil\DLL\..\include" -Iinclude\visutils -I3rdparty\opencv\include -I3rdparty\cub -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DWIN32 -DWIN64 -DNDEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o bin\x64\Release\VisCuda\ocv_kernel_ext.cu.obj "C:\bsa_0736_3380_iQ500\branch\8.3\vision\modules\viscuda\ocv_kernel_ext.cu" 
1>  ocv_kernel_ext.cu
1>CUDACOMPILE : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 8.0.targets(689,9): error MSB3722: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env --cl-version 2013 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64"  -Iinclude\VisCuda -Iinclude\logger -Iinclude\memory -I"C:\Program Files\Matrox Imaging\Mil\DLL\..\include" -Iinclude\visutils -I3rdparty\opencv\include -I3rdparty\cub -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DWIN32 -DWIN64 -DNDEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o bin\x64\Release\VisCuda\ocv_kernel_ext.cu.obj "C:\bsa_0736_3380_iQ500\branch\8.3\vision\modules\viscuda\ocv_kernel_ext.cu"" exited with code 5. Please verify that you have sufficient rights to run this command.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Comment by dumerrill** [comment]
I'm afraid this is a known compiler bug in Toolkit 8.0.6x.  Alternatives include:

- Clone (or rebase) CUB `master` branch (or upcoming v1.7.1, when snapped), which has a work-around for CUDA 8.0.6x
- Use [the newer CUDA Toolkit 9.x](https://developer.nvidia.com/cuda-toolkit/whatsnew) (currently in RC), which addresses the issue
- Use [the older CUDA Toolkit 8.0.44 available in the archives](https://developer.nvidia.com/cuda-80-download-archive), the delta from 8.0.6x mostly being performance of libraries (CUBLAS, CUDNN, etc.)
